### ISSUE TITLE
Adding a conda-forge package

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/jupyterlab-nvdashboard#11]
Not totally sure how much sense this makes given the JupyterLab packaging model ATM (unless things have changed since I last looked). Though figured I'd raise this interest anyways.

It would be nice to have a conda-forge package to make this installable with Conda. Ideally this would handle installing the Python components and installing the extension with JupyterLab.

**Comment by jacobtomlinson** [comment]
Yeah this would be nice as an alternative to the `pip` install. Mainly because there are some heavy dependencies here (`bokeh`, `numpy`, etc).

**Comment by jacobtomlinson** [comment]
conda-forge/staged-recipes#10446

**Comment by jacobtomlinson** [comment]
@jakirkham I've opened a PR on conda forge. Could you take a look and check this satisfies this issue?

**Comment by jacobtomlinson** [comment]
The recipe has now been merged. Installing with `conda install -c conda-forge jupyterlab-nvdashboard` works, however it requires an additional `jupyter lab build` once it has been installed.

I suspect this is related to `nodejs` being missing and I've raised conda-forge/jupyterlab-nvdashboard-feedstock#1 to hopefully address it.

**Comment by jhamman** [comment]
@jacobtomlinson - can this be closed now (i.e. should I assume the conda-forge package is fully operational and does not require an extra `jupyter lab build...` step)?

**Comment by jacobtomlinson** [comment]
Things don't seem to be perfect in the conda install at the moment. You may still need the extra build, the one in the recipe doesn't seem to take effect.

But yes I'll close this out from here, thanks @jhamman.
