### ISSUE TITLE
The extension "jupyterlab-nvdashboard" does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by marques576** [rapidsai/jupyterlab-nvdashboard#137]
Extension Installation Error
An error occurred installing <code>jupyterlab-nvdashboard</code>.

Error message:

The extension "jupyterlab-nvdashboard" does not yet support the current version of JupyterLab.

![image](https://user-images.githubusercontent.com/23244686/191726387-d663aaf6-5f51-4bb9-a93f-d1c580b2e682.png)

**Comment by samuel-vitorino** [comment]
I have the same issue, any ETA to when it will be compatible?
