### ISSUE TITLE
README should include an image or gif of nvdashboard running in Jupyterlab

### ISSUE THREAD

**Issue by beckernick** [rapidsai/jupyterlab-nvdashboard#142]
To help people understand how useful this tool is, we should add an image or gif to the README illustrating what nvdashboard running looks like.

Feel free to assign this to me.

**Comment by jacobtomlinson** [comment]
Yeah absolutely! I'm surprised we haven't done this already.

We could just grab the GIF from this blog post and use it https://developer.nvidia.com/blog/gpu-dashboards-in-jupyter-lab/.

Do you want to raise a PR @beckernick?

**Comment by beckernick** [comment]
Yes, thanks for the tip. Will put one up with that GIF shortly.

**Comment by beckernick** [comment]
Initially used the gif from the blog, but decided to start with the existing demo.gif which is quite similar.
