### ISSUE TITLE
Dashboard not showing even server and frontend look fine

### ISSUE THREAD

**Issue by fabiosanger** [rapidsai/jupyterlab-nvdashboard#152]
I built a custom docker container from FROM jupyter/base-notebook:python-3.9.12. After installing cuda+cudnn I pip installed, on base env:

```
# Installing GPU Dashboard
RUN pip install "jupyterlab>3.5" \
                jupyterlab-nvdashboard \
                jupyter-resource-usage \
                "ipywidgets>8" \
                bokeh==3.0.3 
```
but the dashboard is not loading

> (base) root@d86f26acebbd:~# jupyter server extension list
> Config dir: /home/jovyan/.jupyter
> 
> Config dir: /opt/conda/etc/jupyter
>     jupyter_server_proxy enabled
>     - Validating jupyter_server_proxy...
>       jupyter_server_proxy  OK
>     jupyter_resource_usage enabled
>     - Validating jupyter_resource_usage...
>       jupyter_resource_usage 0.7.1 OK
>     jupyter_server_fileid enabled
>     - Validating jupyter_server_fileid...
>       jupyter_server_fileid 0.6.0 OK
>     jupyter_server_ydoc enabled
>     - Validating jupyter_server_ydoc...
>       jupyter_server_ydoc 0.6.1 OK
>     jupyterlab enabled
>     - Validating jupyterlab...
>       jupyterlab 3.6.1 OK
>     jupyterlab_nvdashboard enabled
>     - Validating jupyterlab_nvdashboard...
>       jupyterlab_nvdashboard  OK
>     nbclassic enabled
>     - Validating nbclassic...
>       nbclassic  OK
>     notebook_shim enabled
>     - Validating notebook_shim...
>       notebook_shim  OK
> 
> Config dir: /usr/local/etc/jupyter

> (base) root@d86f26acebbd:~# jupyter labextension list
> JupyterLab v3.6.1
> /opt/conda/share/jupyter/labextensions
>         jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
>         jupyterlab-nvdashboard v0.7.0 enabled OK (python, jupyterlab_nvdashboard)
>         @jupyterlab/server-proxy v3.2.2 enabled OK
>         @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
>         @jupyter-server/resource-usage v0.7.1 enabled OK (python, jupyter-resource-usage)

**Comment by jacobtomlinson** [comment]
I see `jupyterlab_nvdashboard OK` so the extension is being loaded.

When you say "the dashboard is not loading" what do you mean?

**Comment by fabiosanger** [comment]
The tab does not appear as in this picture. By the way it seams to work if I stall jupyterlab_nvdashboard to a specific env. 
![image](https://user-images.githubusercontent.com/118277438/219082714-37e6e48a-e6ac-4a06-baa7-77ea86ad7b5c.png)

**Comment by jacobtomlinson** [comment]
You need to install it into the same env that you have installed Jupyter.

**Comment by fabiosanger** [comment]
Jupyter is installed on the base env as well.

**Comment by jacobtomlinson** [comment]
I'm afraid I am not able to reproduce your issue with the following steps.

```dockerfile
FROM jupyter/base-notebook:python-3.9.12

RUN pip install "jupyterlab>3.5" \
                jupyterlab-nvdashboard \
                jupyter-resource-usage \
                "ipywidgets>8" \
                bokeh==3.0.3
```

```console
$ docker build -t jacobtomlinson/nvdash-test:dev .
...
Successfully tagged jacobtomlinson/nvdash-test:dev

$ docker run --rm -it -p 8888:8888 --gpus=all jacobtomlinson/nvdash-test:dev
...
[C 2023-02-16 10:09:40.157 ServerApp]

    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-7-open.html
    Or copy and paste one of these URLs:
        http://368b83fffd9d:8888/lab?token=d5cfb4f7aad38a23e8a9d30c85c81217df7d881e19a85f7c
     or http://127.0.0.1:8888/lab?token=d5cfb4f7aad38a23e8a9d30c85c81217df7d881e19a85f7c
```

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1610850/219335364-1a0fc9fa-24ff-47bb-b20d-e524eb6cc325.png">

**Comment by fabiosanger** [comment]
i built the same docrefile as yours, when i run

> [I 2023-02-16 11:05:44.805 ServerApp] jupyterlab | extension was successfully loaded.
> [W 2023-02-16 11:05:44.805 ServerApp] jupyterlab_nvdashboard | extension failed loading with message: _load_jupyter_server_extension function was not found.
> [E 2023-02-16 11:05:44.805 ServerApp] jupyterlab_nvdashboard | stack trace
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 355, in load_extension
>         extension.load_all_points(self.serverapp)
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 229, in load_all_points
>         return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 229, in <listcomp>
>         return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 222, in load_point
>         return point.load(serverapp)
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 147, in load
>         loader = self._get_loader()
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 116, in _get_loader
>         loader = get_loader(loc)
>       File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/utils.py", line 37, in get_loader
>         raise ExtensionLoadingError(msg) from None
>     jupyter_server.extension.utils.ExtensionLoadingError: _load_jupyter_server_extension function was not found.
> [I 2023-02-16 11:05:44.810 ServerApp] nbclassic | extension was successfully loaded.
> [I 2023-02-16 11:05:44.811 ServerApp] Serving notebooks from local directory: /home/jovyan
> [I 2023-02-16 11:05:44.811 ServerApp] Jupyter Server 1.23.6 is running at:
> [I 2023-02-16 11:05:44.811 ServerApp] http://localhost:5000/lab?token=86ebe0f6b0f01bd3929a0907b8c1846ce7be43e9f773a13b
> [I 2023-02-16 11:05:44.811 ServerApp]  or http://127.0.0.1:5000/lab?token=86ebe0f6b0f01bd3929a0907b8c1846ce7be43e9f773a13b
> [I 2023-02-16 11:05:44.811 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

> (base) jovyan@ffc2f7352222:~$ jupyter labextension list
> JupyterLab v3.6.1
> /opt/conda/share/jupyter/labextensions
>         jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
>         jupyterlab-nvdashboard v0.7.0 enabled OK (python, jupyterlab_nvdashboard)
>         @jupyterlab/server-proxy v3.2.2 enabled OK
>         @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
>         @jupyter-server/resource-usage v0.7.1 enabled OK (python, jupyter-resource-usage)

> (base) jovyan@ffc2f7352222:~$ jupyter server extension list
> Config dir: /home/jovyan/.jupyter
> 
> Config dir: /opt/conda/etc/jupyter
>     jupyter_server_proxy enabled
>     - Validating jupyter_server_proxy...
>       jupyter_server_proxy  OK
>     jupyter_resource_usage enabled
>     - Validating jupyter_resource_usage...
>       jupyter_resource_usage 0.7.1 OK
>     jupyter_server_fileid enabled
>     - Validating jupyter_server_fileid...
>       jupyter_server_fileid 0.6.0 OK
>     jupyter_server_ydoc enabled
>     - Validating jupyter_server_ydoc...
>       jupyter_server_ydoc 0.6.1 OK
>     jupyterlab enabled
>     - Validating jupyterlab...
>       jupyterlab 3.6.1 OK
>     jupyterlab_nvdashboard enabled
>     - Validating jupyterlab_nvdashboard...
>        X validation failed
>     nbclassic enabled
>     - Validating nbclassic...
>       nbclassic  OK
>     notebook_shim enabled
>     - Validating notebook_shim...
>       notebook_shim  OK
> 
> Config dir: /usr/local/etc/jupyter

**Comment by fabiosanger** [comment]
Thanks i got it working, i had to install "ipywidgets>8" on base and then install lab on work_env. but for instance machine resources does not work 500 error.
