### ISSUE TITLE
NVDashboard for multi-node systems

### ISSUE THREAD

**Issue by vilmara** [rapidsai/jupyterlab-nvdashboard#34]
Hi all, how can I configure NVDashboard to monitor the entire GPU resources for multi-node systems?. Currently, I have 2 nodes with 4 GPU's each (total 8 GPU's); however, the dashboard is monitoring only the GPU resources for one machine.

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

It is not possible to monitor multi-node systems with nvdashboard. 

The dashboard uses [pynvml](https://pypi.org/project/pynvml/) to access information about the GPUs attached to the machine that is running Jupyter Lab. There is no way currently for it to be able to discover information about GPUs on another system.

A workaround would be to run the dashboard from both machines in standalone mode and open them side by side in your browser.

I've just raised #35 to make running in standalone mode easier. In the meantime here is a very unpleasant one-liner to run in standalone mode on port `8000`.

```console
$ python $(python -c 'import os.path; import jupyterlab_nvdashboard; print(os.path.join(os.path.dirname(os.path.realpath(jupyterlab_nvdashboard.__file__)), "server.py"))') 8000
```

**Comment by jacobtomlinson** [comment]
With v0.2.0 you can now run `nvdashboard` from the terminal to start the standalone dashboard on port `8000`.

**Comment by jacobtomlinson** [comment]
An alternative that can be used today is to use the Dask dashboard which has multi-GPU multi-node support.

This would involve starting a [Dask CUDA](https://github.com/rapidsai/dask-cuda) worker on each node in the system and then using the [Dask Lab Extension](https://github.com/dask/dask-labextension) to view the GPU utilisation dashboard.

This is not a long term solution, especially if you are not using Dask for your computation. But may be a sticking plaster for today.

However this may not be useful if running Kubernetes as it is not possible for one GPU to be assigned to multiple pods.
