### ISSUE TITLE
Dashboard error with bokeh 2.0.0

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/jupyterlab-nvdashboard#49]
With the new bokeh 2.0 packages added to Conda-forge a couple of days back, the dashboards are now empty and I see the following error:

```
ERROR:tornado.application:Uncaught exception GET /GPU-Utilization/ws (::1)
HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/GPU-Utilization/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "lib/python3.7/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "lib/python3.7/site-packages/bokeh/server/views/ws.py", line 123, in open
    raise ProtocolError("Subprotocol header is not 'bokeh'")
bokeh.protocol.exceptions.ProtocolError: Subprotocol header is not 'bokeh'
```

Downgrading to 1.4.0 works as expected

**Comment by jakirkham** [comment]
Thanks Ayush! Yeah they probably broke something, but this is expected as they bumped the major version. Adding PR ( https://github.com/rapidsai/jupyterlab-nvdashboard/pull/50 ) to constrain this to Bokeh 1 for now.

**Comment by adrifloresm** [comment]
Can this fix be added to `pip install jupyterlab-nvdashboard` and `jupyter labextension install jupyterlab-nvdashboard` . I am installing the dashboard through Docker with those commands. thanks!

**Comment by jacobtomlinson** [comment]
This has now been released
