### ISSUE TITLE
Compatibility for JupyterLab ^2.0

### ISSUE THREAD

**Issue by sshakeri** [rapidsai/jupyterlab-nvdashboard#51]
Seems like currently on Jupyter 1.x is supported based on packages.json https://github.com/rapidsai/jupyterlab-nvdashboard/blob/branch-0.3/package.json#L33

**Comment by jakirkham** [comment]
Yeah it’s unsupported atm.

**Comment by jakirkham** [comment]
cc @jacobtomlinson (for awareness)

**Comment by jacobtomlinson** [comment]
Thanks @jakirkham.

There are some changes we will need to make to support JL 2.0. Similar to [the ones made in the Dask Lab Extension](https://github.com/dask/dask-labextension/pull/119).

**Comment by jakirkham** [comment]
Thanks Jacob. Yeah was meaning to mention it earlier, but forgot. 😄

We also tried to pin down Bokeh short-term ( https://github.com/rapidsai/jupyterlab-nvdashboard/pull/50 ), but it sounds like you may already know how to fix this correctly 🙂

**Comment by jacobtomlinson** [comment]
Fixed in #62
