### ISSUE TITLE
Remote GPU Usage

### ISSUE THREAD

**Issue by quasiben** [rapidsai/jupyterlab-nvdashboard#61]
Lately, I've been using dask/nvdashboard in multinode setups.  Can nvdashboard be extended to report GPU memory usage on remote workers ?

cc @jacobtomlinson

**Comment by jacobtomlinson** [comment]
This has been raised before in #34 and #45.

I feel like we have a few options here, ordered from least complex to most:

- Run nvdashboard manually on each node and open each dashboard in a new window
- Use Dask's built in GPU dashboards (may not make sense if you aren't using Dask)
- Extend the existing dashboards to be able to collate data from multiple instances of nvdashboard. This would probably still require the user to run nvdashboard on each node.

This is a highly requested feature so perhaps we should give it some more time and thought.

**Comment by quasiben** [comment]
Thanks for the response for other the "secret" dask dashobard is at:

> http://URL:8787/individual-gpu-memory
