### ISSUE TITLE
libnvidia-ml.so.1 not available on Tegra platform

### ISSUE THREAD

**Issue by Tiemichael** [rapidsai/jupyterlab-nvdashboard#65]
As libnvidia-ml.so.1 is not available on Tegra platform, but required by jupyterlab-nvdashboard  the dashboard is not running on devices like Jetson Nano and many others.
Is there any chance to 'replace' libnvidia-ml.so.1 with a shared lib available also on tegra?

**Comment by jakirkham** [comment]
This requirement comes from [pynvml]( https://github.com/gpuopenanalytics/pynvml ). That said, I'm not sure how we would support equivalent functionality without [NVML]( https://developer.nvidia.com/nvidia-management-library-nvml ). Do you have a suggestion?

**Comment by Tiemichael** [comment]
Sorry, no idea how to overcome ...
Thanks for the quick reply!
