### ISSUE TITLE
Upgrading to Bokeh 2

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/jupyterlab-nvdashboard#66]
Current we are pinning `jupyterlab-nvdashboard` to [`bokeh` version `1`]( https://github.com/rapidsai/jupyterlab-nvdashboard/blob/1f0e39a5a0996667d1dde9226e654030020359d8/conda/recipes/jupyterlab-nvdashboard/meta.yaml#L29 ). Would be good to fix any remaining compatibility issues so `bokeh` version `2` can be used.

**Comment by jacobtomlinson** [comment]
Agreed. I think Bokeh `2.1` has had a bunch of issues, so I'm tempted to hold off until their next patch release.

**Comment by jakirkham** [comment]
Do you happen to recall the issues?

**Comment by owenlamont** [comment]
I was just about to request this too... would be nice to install nvdashboard in Python environments that already have Bokeh 2+. I don't know how much work is involved in this but happy to try and help when you think it's good to go ahead.

**Comment by owenlamont** [comment]
One issue we have with Bokeh 2 on conda is if a user tries to install nvdashboard into a Python environment that already has Bokeh 2 conda won't force them to downgrade Bokeh - they will just get an older version of nvdashboard that pre-dates the Bokeh<2 requirement which will be broken in their environment. I'm not sure if pip has the same issue... I didn't test that. I don't know if there is a  way to remove the pre 0.3 recipes from conda-forge @jakirkham

**Comment by jakirkham** [comment]
Probably the thing to do is hot-fix older `jupyterlab-nvdashboard` packages to have this constraint as well. For example here's how we addressed a similar issue with `distributed` ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/32 ).

**Comment by jakirkham** [comment]
FWIW [Bokeh 2.1.1.]( https://docs.bokeh.org/en/latest/docs/releases.html#release-2-1-1 ) shipped today. Not sure if that includes fixes to the issues observed, but may be worth checking 🙂

**Comment by owenlamont** [comment]
> Probably the thing to do is hot-fix older `jupyterlab-nvdashboard` packages to have this constraint as well. For example here's how we addressed a similar issue with `distributed` ( [conda-forge/conda-forge-repodata-patches-feedstock#32](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/32) ).

Good to know. I'll try to look into making the patches this coming weekend for conda-forge.

**Comment by AjayThorve** [comment]
+ 1 for this. I just finished upgrading cuxfilter to bokeh 2.1.1, and the issues were fairly straight forward to fix.

**Comment by jacobtomlinson** [comment]
Yeah 2.1.1 is the release I was waiting for. Thanks for testing things @AjayThorve. I'll open a PR to update the version.
