### ISSUE TITLE
System dashboards (machine resources) active even in absence of GPU

### ISSUE THREAD

**Issue by twrobinson** [rapidsai/jupyterlab-nvdashboard#68]
Would it be possible to have the "machine resources" tab functional even when the GPU is not found? Imagine a situation where some nodes are GPU-enabled and others are not. It would be useful to still make the CPU and memory metrics available.

**Comment by twrobinson** [comment]
Moreover, at the moment if the extension is installed and enabled, but no GPU is found, then a user gets a constant stream of error messages in their log:

pynvml.nvml.NVMLError_DriverNotLoaded: Driver Not Loaded

**Comment by jacobtomlinson** [comment]
Thanks for raising this @twrobinson. I've moved your second comment out into a separate issue (#69).

I can understand the value of having CPU metrics on non GPU systems. There are many existing tools for CPU monitoring, such as [jupyterlab-system-monitor](https://github.com/jtpio/jupyterlab-system-monitor). Given that this extension is primarily focussed on GPU metrics it may be more appropriate to use another extension on non GPU systems.

**Comment by twrobinson** [comment]
Hi Jacob, thanks for your comment, and of course for creating a cool extension! 

I can understand your point. 

Thanks for creating issue #69 . You can close this one if you like.
