### ISSUE TITLE
Add graceful failure on non GPU systems

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/jupyterlab-nvdashboard#69]
...at the moment if the extension is installed and enabled, but no GPU is found, then a user gets a constant stream of error messages in their log:

pynvml.nvml.NVMLError_DriverNotLoaded: Driver Not Loaded

_Originally posted by @twrobinson in https://github.com/rapidsai/jupyterlab-nvdashboard/issues/68#issuecomment-651846814_

**Comment by owenlamont** [comment]
Is this a duplicate of [issue 33](https://github.com/rapidsai/jupyterlab-nvdashboard/issues/33) @jacobtomlinson?

**Comment by jacobtomlinson** [comment]
Yes thanks for spotting this!
