### ISSUE TITLE
Add JupyterLab 3 support

### ISSUE THREAD

**Issue by owenlamont** [rapidsai/jupyterlab-nvdashboard#84]
Not sure if this is already on the roadmap but if we could support JupyterLab 3's [prebuilt/federated extensions](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0) that sounds like it would give an improved user experience. As I understand them, it means users no longer need to jupyterlab install or build the extension to use it - just pip or conda install the jupyterlab-nvdashboard package and the extension works out the box.

**Comment by jacobtomlinson** [comment]
This would be great!

**Comment by divyanshsinghvi** [comment]
I would need this feature enabled in my work. Is there some work around for jupyterlab 3's , or else if someone could point me to the necessary changes to be done to enable it for jupyterlab 3's. I would be happy to contribute to this enhancement.

**Comment by Data-drone** [comment]
Here is a guide: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html

**Comment by marius311** [comment]
I have absolutely no experience with JL plugins but I just followed that guide, which ammounts to nothing more than cloning this repo and running

```
python -m jupyterlab.upgrade_extension .
```

then following the usual dev install instructions in this repo's readme, and it works:

![image](https://user-images.githubusercontent.com/1510968/113258286-9c426c00-9280-11eb-8ec6-95740fc6d65a.png)

Hopefully this is encouraging to a dev here that would also know how to package / release a new version.

**Comment by txu0393** [comment]
@jacobtomlinson
Are there any updates on the release timeline for 0.6.0?
We would like to use the latest version with JLab 3 support!

**Comment by jacobtomlinson** [comment]
0.6.0 is out now with JL3 support. Thanks for the patience here!
