### ISSUE TITLE
Correctly categorizing the card in the Launcher

### ISSUE THREAD

**Issue by vidosits** [rapidsai/jupyterlab-nvdashboard#98]
Hey, would it be possible to categorize the extension's launch card correctly so that it doesn't show up in Notebooks?
![image](https://user-images.githubusercontent.com/33751628/118320715-e9ab2d80-b4fc-11eb-9a08-d675f8f189a1.png)
According to JupyterLab docs it should be possible:
- [JupyterLab docs](https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html#launcher)
- [JupyterLab API docs](https://jupyterlab.readthedocs.io/en/latest/api/interfaces/launcher.ilauncher.iitemoptions.html#category)

**Comment by jacobtomlinson** [comment]
Strange I don't see this.

![image](https://user-images.githubusercontent.com/1610850/118828272-0658b400-b8b5-11eb-9812-62b53b8ef26a.png)

Could you share your Jupyter Lab version?

**Comment by jacobtomlinson** [comment]
Interesting. I'm on `3.0.11` so it must've snuck in. 

We don't actually add anything to the launcher explicitly so it must be discovering it somehow.

**Comment by vidosits** [comment]
Yeah, very strange. In the docs they seem to explicitly require the usage of `ILauncher`, but I haven't been able to find a reference to that token in this repo.

[JupyterLab docs](https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html#launcher)
[JupyterLab API docs](https://jupyterlab.readthedocs.io/en/latest/api/interfaces/launcher.ilauncher.iitemoptions.html#category)

I also don't any mention of `Card` or `Launcher` in the [changelogs](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0-11) since `3.0.11`.

Just to be sure, I also tested with an empty environment with Docker:

```Dockerfile
FROM continuumio/miniconda3
RUN apt update
RUN apt install -y gcc
RUN pip install --pre jupyterlab_nvdashboard
ENTRYPOINT ["jupyter", "lab", "--allow-root", "--ip=0.0.0.0"]

```

**Comment by vidosits** [comment]
Doesn't seem to be related to Jupyter's minor version, I can also reproduce it on `3.0.11`:
![image](https://user-images.githubusercontent.com/33751628/119375622-4e177b00-bcbb-11eb-8321-933880bc3c4b.png)

```Dockerfile
FROM python:3.7
RUN apt update
RUN apt install -y gcc
RUN pip install jupyterlab==3.0.11
RUN pip install --pre jupyterlab_nvdashboard
ENTRYPOINT ["jupyter", "lab", "--allow-root", "--ip=0.0.0.0"]
```

**Comment by jacobtomlinson** [comment]
How strange. 

@ian-r-rose I know you don't work on this project but do you have any idea what is going on here? Are there any docs you could point me to?

**Comment by vidosits** [comment]
@jacobtomlinson Have you been able to reproduce it on your end (maybe w/ Docker?). It's really strange that JupyterLab v3.0.11 gives a different setup to you than for me, although I'm not sure if you've checked with v0.6.0 of this project.

**Comment by ian-r-rose** [comment]
This is an effect of the `jupyterlab-server-proxy` labextension (note the "lab", it's independent of the `jupyter-server-proxy server extension). Some of the maintainers there like the idea of putting proxied applications on top, and hack it into the notebooks category. See [this issue](https://github.com/jupyterhub/jupyter-server-proxy/issues/145), started by yours truly.

I usually avoid installing the `jupyterlab-server-proxy` package for this reason. It would be best if somebody could figure out an upstream fix that satisfies all parties, though I haven't weighed in recently, sorry to say.
